CREATE TABLE IF NOT EXISTS `route_permissions` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_key` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `route_name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_route_permissions_route_name` (`route_name`),
  KEY `idx_route_permissions_group` (`group_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_route_permissions` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` bigint UNSIGNED NOT NULL,
  `route_permission_id` bigint UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_route_permissions` (`user_id`,`route_permission_id`),
  KEY `idx_user_route_permissions_route` (`route_permission_id`),
  CONSTRAINT `fk_user_route_permissions_user`
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_user_route_permissions_route`
    FOREIGN KEY (`route_permission_id`) REFERENCES `route_permissions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `route_permissions` (`group_key`, `route_name`, `label`, `created_at`) VALUES
('dashboard', 'dashboard.index', 'Acessar dashboard executivo', NOW()),
('dashboard', 'busca.index', 'Acessar busca global', NOW()),
('dashboard', 'logs.index', 'Acessar logs e auditoria', NOW()),
('dashboard', 'changelog.index', 'Acessar versionamento e changelog', NOW()),
('config', 'config.index', 'Acessar configurações', NOW()),
('config', 'config.branding.save', 'Salvar branding', NOW()),
('config', 'config.favicon.save', 'Salvar favicon', NOW()),
('config', 'config.modules.save', 'Salvar módulos', NOW()),
('config', 'config.smtp.save', 'Salvar SMTP do sistema', NOW()),
('config', 'config.access-profiles.save', 'Salvar perfil de acesso', NOW()),
('config', 'config.access-profiles.delete', 'Excluir perfil de acesso', NOW()),
('config', 'config.servicos.store', 'Cadastrar serviço', NOW()),
('config', 'config.servicos.update', 'Editar serviço', NOW()),
('config', 'config.servicos.delete', 'Excluir serviço', NOW()),
('config', 'config.status.store', 'Cadastrar status', NOW()),
('config', 'config.status.update', 'Editar status', NOW()),
('config', 'config.status.delete', 'Excluir status', NOW()),
('config', 'config.formas.store', 'Cadastrar forma de envio', NOW()),
('config', 'config.formas.update', 'Editar forma de envio', NOW()),
('config', 'config.formas.delete', 'Excluir forma de envio', NOW()),
('config', 'config.users.store', 'Cadastrar usuário', NOW()),
('config', 'config.users.update', 'Editar usuário', NOW()),
('config', 'config.users.delete', 'Excluir usuário', NOW()),
('clientes', 'clientes.index', 'Acessar módulo clientes', NOW()),
('clientes', 'clientes.avulsos', 'Listar avulsos', NOW()),
('clientes', 'clientes.avulsos.create', 'Novo avulso', NOW()),
('clientes', 'clientes.avulsos.store', 'Salvar avulso', NOW()),
('clientes', 'clientes.avulsos.edit', 'Editar avulso', NOW()),
('clientes', 'clientes.avulsos.update', 'Atualizar avulso', NOW()),
('clientes', 'clientes.avulsos.delete', 'Excluir avulso', NOW()),
('clientes', 'clientes.contatos', 'Listar contatos', NOW()),
('clientes', 'clientes.contatos.create', 'Novo contato', NOW()),
('clientes', 'clientes.contatos.store', 'Salvar contato', NOW()),
('clientes', 'clientes.contatos.edit', 'Editar contato', NOW()),
('clientes', 'clientes.contatos.update', 'Atualizar contato', NOW()),
('clientes', 'clientes.contatos.delete', 'Excluir contato', NOW()),
('clientes', 'clientes.condominos', 'Listar condôminos', NOW()),
('clientes', 'clientes.condominios', 'Listar condomínios', NOW()),
('clientes', 'clientes.condominios.create', 'Novo condomínio', NOW()),
('clientes', 'clientes.condominios.store', 'Salvar condomínio', NOW()),
('clientes', 'clientes.condominios.edit', 'Editar condomínio', NOW()),
('clientes', 'clientes.condominios.update', 'Atualizar condomínio', NOW()),
('clientes', 'clientes.condominios.delete', 'Excluir condomínio', NOW()),
('clientes', 'clientes.unidades', 'Listar unidades', NOW()),
('clientes', 'clientes.unidades.create', 'Nova unidade', NOW()),
('clientes', 'clientes.unidades.store', 'Salvar unidade', NOW()),
('clientes', 'clientes.unidades.edit', 'Editar unidade', NOW()),
('clientes', 'clientes.unidades.update', 'Atualizar unidade', NOW()),
('clientes', 'clientes.unidades.delete', 'Excluir unidade', NOW()),
('clientes', 'clientes.config', 'Configurar tipos de clientes', NOW()),
('clientes', 'clientes.config.types.store', 'Cadastrar tipo', NOW()),
('clientes', 'clientes.attachments.download', 'Baixar anexo cliente', NOW()),
('clientes', 'clientes.attachments.delete', 'Excluir anexo cliente', NOW()),
('cobrancas', 'cobrancas.dashboard', 'Acessar dashboard de cobrança', NOW()),
('cobrancas', 'cobrancas.index', 'Listar OS de cobrança', NOW()),
('cobrancas', 'cobrancas.create', 'Nova OS de cobrança', NOW()),
('cobrancas', 'cobrancas.store', 'Salvar OS de cobrança', NOW()),
('cobrancas', 'cobrancas.import.index', 'Acessar importação de inadimplência', NOW()),
('cobrancas', 'cobrancas.import.preview', 'Analisar planilha de inadimplência', NOW()),
('cobrancas', 'cobrancas.import.show', 'Visualizar lote de importação de inadimplência', NOW()),
('cobrancas', 'cobrancas.import.process', 'Processar lote de inadimplência', NOW()),
('cobrancas', 'cobrancas.agreement.edit', 'Editar termo de acordo da OS', NOW()),
('cobrancas', 'cobrancas.agreement.save', 'Salvar customização do termo de acordo', NOW()),
('cobrancas', 'cobrancas.agreement.pdf', 'Gerar PDF do termo de acordo', NOW()),
('cobrancas', 'cobrancas.show', 'Visualizar OS de cobrança', NOW()),
('cobrancas', 'cobrancas.edit', 'Editar OS de cobrança', NOW()),
('cobrancas', 'cobrancas.update', 'Atualizar OS de cobrança', NOW()),
('cobrancas', 'cobrancas.delete', 'Excluir OS de cobrança', NOW()),
('cobrancas', 'cobrancas.timeline.store', 'Adicionar andamento na OS de cobrança', NOW()),
('cobrancas', 'cobrancas.attachments.upload', 'Enviar anexo no GED da cobrança', NOW()),
('cobrancas', 'cobrancas.attachments.download', 'Baixar anexo do GED da cobrança', NOW()),
('cobrancas', 'cobrancas.attachments.delete', 'Excluir anexo do GED da cobrança', NOW()),
('propostas', 'propostas.dashboard', 'Acessar dashboard de propostas', NOW()),
('propostas', 'propostas.index', 'Listar propostas', NOW()),
('propostas', 'propostas.export.csv', 'Exportar CSV', NOW()),
('propostas', 'propostas.create', 'Nova proposta', NOW()),
('propostas', 'propostas.store', 'Salvar proposta', NOW()),
('propostas', 'propostas.show', 'Visualizar proposta', NOW()),
('propostas', 'propostas.print', 'Imprimir proposta', NOW()),
('propostas', 'propostas.edit', 'Editar proposta', NOW()),
('propostas', 'propostas.update', 'Atualizar proposta', NOW()),
('propostas', 'propostas.delete', 'Excluir proposta', NOW()),
('propostas', 'propostas.attachments.upload', 'Enviar anexo de proposta', NOW()),
('propostas', 'propostas.attachments.download', 'Baixar anexo de proposta', NOW()),
('propostas', 'propostas.attachments.delete', 'Excluir anexo de proposta', NOW()),
('propostas', 'propostas.document.edit', 'Editar documento premium', NOW()),
('propostas', 'propostas.document.save', 'Salvar documento premium', NOW()),
('propostas', 'propostas.document.preview', 'Visualizar documento premium', NOW()),
('propostas', 'propostas.document.pdf', 'PDF/print documento premium', NOW())
ON DUPLICATE KEY UPDATE
  `group_key` = VALUES(`group_key`),
  `label` = VALUES(`label`);
