@extends('layouts.app')

@section('content')
<x-ancora.section-header title="Configurações" subtitle="Painel inicial de branding, módulos e usuários preservando a mecânica administrativa." />
<div class="grid grid-cols-1 gap-6 xl:grid-cols-3">
    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="text-base font-semibold text-gray-900 dark:text-white">Branding</h3><div class="mt-4 space-y-3">@foreach($settings->whereIn('setting_key', ['app_company','branding_logo_light_path','branding_logo_dark_path','branding_favicon_path']) as $setting)<div class="rounded-2xl border border-gray-200 px-4 py-3 dark:border-gray-800"><div class="text-xs uppercase tracking-[0.18em] text-gray-400">{{ $setting->setting_key }}</div><div class="mt-2 text-sm text-gray-700 dark:text-gray-300 break-all">{{ $setting->setting_value }}</div></div>@endforeach</div></div>
    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="text-base font-semibold text-gray-900 dark:text-white">Módulos</h3><div class="mt-4 space-y-3">@foreach($modules as $module)<div class="flex items-center justify-between rounded-2xl border border-gray-200 px-4 py-3 dark:border-gray-800"><div><div class="font-medium text-gray-900 dark:text-white">{{ $module->name }}</div><div class="text-xs text-gray-500 dark:text-gray-400">{{ $module->slug }}</div></div><span class="rounded-full px-3 py-1 text-xs {{ $module->is_enabled ? 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-300' : 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300' }}">{{ $module->is_enabled ? 'Habilitado' : 'Desligado' }}</span></div>@endforeach</div></div>
    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="text-base font-semibold text-gray-900 dark:text-white">Usuários</h3><div class="mt-4 space-y-3">@foreach($users as $user)<div class="rounded-2xl border border-gray-200 px-4 py-3 dark:border-gray-800"><div class="font-medium text-gray-900 dark:text-white">{{ $user->name }}</div><div class="mt-1 text-xs text-gray-500 dark:text-gray-400">{{ $user->email }} · {{ $user->role }}</div></div>@endforeach</div></div>
</div>
@endsection
