@extends('layouts.app')

@section('content')
<x-ancora.section-header title="Configurações" subtitle="Branding destravado, cadastros-base, usuários, módulos e permissões finas por rota." />
<div class="space-y-6">
    <div class="grid grid-cols-1 gap-6 xl:grid-cols-2">
        <form method="post" action="{{ route('config.branding.save') }}" enctype="multipart/form-data" class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">
            @csrf
            <h3 class="text-base font-semibold text-gray-900 dark:text-white">Branding</h3>
            <div class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2">
                <div><label class="mb-1.5 block text-sm font-medium">Empresa</label><input name="company_name" value="{{ $branding['company_name'] }}" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></div>
                <div><label class="mb-1.5 block text-sm font-medium">E-mail</label><input name="company_email" value="{{ $branding['company_email'] }}" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Telefone</label><input name="company_phone" value="{{ $branding['company_phone'] }}" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Endereço</label><input name="company_address" value="{{ $branding['company_address'] }}" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Logo clara</label><input type="file" name="branding_logo_light" class="block w-full text-sm"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Logo escura</label><input type="file" name="branding_logo_dark" class="block w-full text-sm"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Altura desktop</label><input type="number" name="logo_height_desktop" value="{{ $branding['logo_height_desktop'] }}" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Altura mobile</label><input type="number" name="logo_height_mobile" value="{{ $branding['logo_height_mobile'] }}" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Altura login</label><input type="number" name="logo_height_login" value="{{ $branding['logo_height_login'] }}" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"></div>
                <div><label class="mb-1.5 block text-sm font-medium">Logo premium</label><select name="premium_logo_variant" class="h-11 w-full rounded-xl border border-gray-300 bg-transparent px-4 dark:border-gray-700"><option value="light" @selected($branding['premium_logo_variant']==='light')>Usar logo clara</option><option value="dark" @selected($branding['premium_logo_variant']==='dark')>Usar logo escura</option></select></div>
                <div class="md:col-span-2 flex gap-4 text-xs text-gray-500"><span>Atual: <a class="underline" href="{{ $branding['logo_light_url'] }}" target="_blank">logo clara</a></span><span><a class="underline" href="{{ $branding['logo_dark_url'] }}" target="_blank">logo escura</a></span></div>
                <div class="md:col-span-2"><button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Salvar branding</button></div>
            </div>
        </form>
        <form method="post" action="{{ route('config.favicon.save') }}" enctype="multipart/form-data" class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">
            @csrf
            <h3 class="text-base font-semibold text-gray-900 dark:text-white">Favicon e módulos</h3>
            <div class="mt-5 space-y-4">
                <div><label class="mb-1.5 block text-sm font-medium">Favicon atual</label><a href="{{ $branding['favicon_url'] }}" target="_blank" class="text-sm text-brand-600 underline">Abrir favicon</a></div>
                <div><input type="file" name="branding_favicon" class="block w-full text-sm"></div>
                <button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Salvar favicon</button>
            </div>
            <hr class="my-6 border-gray-200 dark:border-gray-800">
            <h4 class="text-sm font-semibold">Módulos habilitados</h4>
            <form></form>
            <div class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2">
                @foreach($modules as $module)
                    <label class="flex items-center gap-3 rounded-xl border border-gray-200 px-4 py-3 dark:border-gray-800"><input type="checkbox" form="modules-form" name="enabled_modules[]" value="{{ $module->id }}" @checked($module->is_enabled)> {{ $module->name }}</label>
                @endforeach
            </div>
        </form>
        <form id="modules-form" method="post" action="{{ route('config.modules.save') }}" class="hidden">@csrf</form>
    </div>

    <div class="grid grid-cols-1 gap-6 xl:grid-cols-2">
        <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">
            <h3 class="text-base font-semibold">Administradoras e síndicos</h3>
            <form method="post" action="{{ route('config.administradoras.store') }}" class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2">@csrf<input name="name" placeholder="Nome" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><select name="type" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><option value="administradora">Administradora</option><option value="sindico">Síndico</option></select><input name="contact_name" placeholder="Contato" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="phone" placeholder="Telefone" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="email" placeholder="E-mail" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><div class="flex items-center gap-3"><input type="checkbox" name="is_active" value="1" checked> Ativo</div><button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Cadastrar</button></form>
            <div class="mt-6 space-y-4">@foreach($administradoras as $item)<form method="post" action="{{ route('config.administradoras.update', $item) }}" class="rounded-xl border border-gray-200 p-4 dark:border-gray-800">@csrf<div class="grid grid-cols-1 gap-3 md:grid-cols-2"><input name="name" value="{{ $item->name }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><select name="type" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><option value="administradora" @selected($item->type==='administradora')>Administradora</option><option value="sindico" @selected($item->type==='sindico')>Síndico</option></select><input name="contact_name" value="{{ $item->contact_name }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="phone" value="{{ $item->phone }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="email" value="{{ $item->email }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><div class="flex items-center gap-3"><input type="checkbox" name="is_active" value="1" @checked($item->is_active)> Ativo</div></div><div class="mt-3 flex gap-2"><button class="rounded-lg bg-brand-500 px-3 py-2 text-xs text-white">Salvar</button><button formaction="{{ route('config.administradoras.delete', $item) }}" formmethod="POST" onclick="return confirm('Excluir registro?')" class="rounded-lg border border-error-300 px-3 py-2 text-xs text-error-600">Excluir</button></div></form>@endforeach</div>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">
            <h3 class="text-base font-semibold">Serviços, status e forma de envio</h3>
            <div class="mt-4 grid grid-cols-1 gap-6">
                <form method="post" action="{{ route('config.servicos.store') }}" class="grid grid-cols-1 gap-3 md:grid-cols-2">@csrf<input name="name" placeholder="Serviço" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="description" placeholder="Descrição" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Cadastrar serviço</button></form>
                @foreach($servicos as $item)<form method="post" action="{{ route('config.servicos.update', $item) }}" class="rounded-xl border border-gray-200 p-4 dark:border-gray-800">@csrf<div class="grid grid-cols-1 gap-3 md:grid-cols-2"><input name="name" value="{{ $item->name }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="description" value="{{ $item->description }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"></div><div class="mt-3 flex gap-2"><button class="rounded-lg bg-brand-500 px-3 py-2 text-xs text-white">Salvar</button><button formaction="{{ route('config.servicos.delete', $item) }}" formmethod="POST" class="rounded-lg border border-error-300 px-3 py-2 text-xs text-error-600">Excluir</button></div></form>@endforeach
                <hr class="border-gray-200 dark:border-gray-800">
                <form method="post" action="{{ route('config.status.store') }}" class="grid grid-cols-1 gap-3 md:grid-cols-2">@csrf<input name="system_key" placeholder="Chave do status" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="name" placeholder="Nome" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="color_hex" value="#999999" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><div class="flex flex-wrap items-center gap-3 text-sm"><label><input type="checkbox" name="requires_closed_value" value="1"> Exige fechado</label><label><input type="checkbox" name="requires_refusal_reason" value="1"> Exige recusa</label><label><input type="checkbox" name="stop_followup_alert" value="1"> Para alertas</label></div><button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Cadastrar status</button></form>
                @foreach($statusRetorno as $item)<form method="post" action="{{ route('config.status.update', $item) }}" class="rounded-xl border border-gray-200 p-4 dark:border-gray-800">@csrf<div class="grid grid-cols-1 gap-3 md:grid-cols-2"><input name="system_key" value="{{ $item->system_key }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="name" value="{{ $item->name }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="color_hex" value="{{ $item->color_hex }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><div class="flex flex-wrap items-center gap-3 text-sm"><label><input type="checkbox" name="requires_closed_value" value="1" @checked($item->requires_closed_value)> Exige fechado</label><label><input type="checkbox" name="requires_refusal_reason" value="1" @checked($item->requires_refusal_reason)> Exige recusa</label><label><input type="checkbox" name="stop_followup_alert" value="1" @checked($item->stop_followup_alert)> Para alertas</label></div></div><div class="mt-3 flex gap-2"><button class="rounded-lg bg-brand-500 px-3 py-2 text-xs text-white">Salvar</button><button formaction="{{ route('config.status.delete', $item) }}" formmethod="POST" class="rounded-lg border border-error-300 px-3 py-2 text-xs text-error-600">Excluir</button></div></form>@endforeach
                <hr class="border-gray-200 dark:border-gray-800">
                <form method="post" action="{{ route('config.formas.store') }}" class="grid grid-cols-1 gap-3 md:grid-cols-2">@csrf<input name="name" placeholder="Forma de envio" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="icon_class" placeholder="fa-solid fa-envelope" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="color_hex" value="#999999" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Cadastrar forma</button></form>
                @foreach($formasEnvio as $item)<form method="post" action="{{ route('config.formas.update', $item) }}" class="rounded-xl border border-gray-200 p-4 dark:border-gray-800">@csrf<div class="grid grid-cols-1 gap-3 md:grid-cols-2"><input name="name" value="{{ $item->name }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="icon_class" value="{{ $item->icon_class }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input name="color_hex" value="{{ $item->color_hex }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"></div><div class="mt-3 flex gap-2"><button class="rounded-lg bg-brand-500 px-3 py-2 text-xs text-white">Salvar</button><button formaction="{{ route('config.formas.delete', $item) }}" formmethod="POST" class="rounded-lg border border-error-300 px-3 py-2 text-xs text-error-600">Excluir</button></div></form>@endforeach
            </div>
        </div>
    </div>

    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">
        <h3 class="text-base font-semibold">Usuários, módulos e permissões por rota</h3>
        <form method="post" action="{{ route('config.users.store') }}" class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-4">@csrf<input name="name" placeholder="Nome" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input type="email" name="email" placeholder="email@dominio.com" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input type="password" name="password" placeholder="Senha" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><select name="role" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><option value="comum">Comum</option><option value="superadmin">Superadmin</option></select><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" checked> Ativo</label><div class="md:col-span-3"><button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Cadastrar usuário</button></div></form>
        <div class="mt-6 space-y-5">@foreach($users as $user)<form method="post" action="{{ route('config.users.update', $user) }}" class="rounded-xl border border-gray-200 p-5 dark:border-gray-800">@csrf<div class="grid grid-cols-1 gap-3 md:grid-cols-4"><input name="name" value="{{ $user->name }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input type="email" name="email" value="{{ $user->email }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><input type="password" name="password" placeholder="Nova senha (opcional)" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><select name="role" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><option value="comum" @selected($user->role==='comum')>Comum</option><option value="superadmin" @selected($user->role==='superadmin')>Superadmin</option></select><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($user->is_active)> Ativo</label></div><div class="mt-4 grid grid-cols-1 gap-6 xl:grid-cols-2"><div><h4 class="mb-2 text-sm font-semibold">Módulos</h4><div class="grid grid-cols-1 gap-2 md:grid-cols-2">@foreach($modules as $module)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="module_permissions[]" value="{{ $module->id }}" @checked($user->modules->contains('id', $module->id))> {{ $module->name }}</label>@endforeach</div></div><div><h4 class="mb-2 text-sm font-semibold">Permissões por rota</h4><div class="max-h-80 space-y-4 overflow-auto rounded-xl border border-gray-200 p-3 dark:border-gray-800">@foreach($routeCatalog as $groupKey => $group)<div><div class="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">{{ $group['label'] }}</div><div class="grid grid-cols-1 gap-2">@foreach(($routePermissionGroups[$groupKey] ?? collect()) as $permission)<label class="flex items-start gap-2 text-sm"><input type="checkbox" name="route_permissions[]" value="{{ $permission->id }}" @checked($user->routePermissions->contains('id', $permission->id))><span>{{ $permission->label }}<span class="block text-xs text-gray-500">{{ $permission->route_name }}</span></span></label>@endforeach</div></div>@endforeach</div></div></div><div class="mt-4 flex gap-2"><button class="rounded-lg bg-brand-500 px-3 py-2 text-xs text-white">Salvar usuário</button>@if(!$user->is_protected)<button formaction="{{ route('config.users.delete', $user) }}" formmethod="POST" onclick="return confirm('Excluir usuário?')" class="rounded-lg border border-error-300 px-3 py-2 text-xs text-error-600">Excluir</button>@endif</div></form>@endforeach</div>
    </div>
</div>
@endsection
