@extends('layouts.app')
@section('content')
<x-ancora.section-header title="Unidades" subtitle="Vínculo entre condomínio, proprietário e locatário.">
    <a href="{{ route('clientes.unidades.create') }}" class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Nova unidade</a>
</x-ancora.section-header>
@include('pages.clientes.partials.subnav')
<div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><form method="get" class="grid grid-cols-1 gap-4 md:grid-cols-3"><input type="search" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Buscar unidade..." class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><select name="condominium_id" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4"><option value="">Todos os condomínios</option>@foreach($condominiumsDropdown ?? [] as $condo)<option value="{{ $condo->id }}" @selected((string)($filters['condominium_id'] ?? '')===(string)$condo->id)>{{ $condo->name }}</option>@endforeach</select><div class="flex gap-3"><button class="rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Filtrar</button><a href="{{ route('clientes.unidades') }}" class="rounded-xl border border-gray-200 px-4 py-3 text-sm font-medium">Limpar</a></div></form></div>
<div class="mt-6 overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">@if($items->count()===0)<div class="p-6"><x-ancora.empty-state icon="fa-solid fa-door-closed" title="Sem unidades" subtitle="Nenhuma unidade foi cadastrada até o momento." /></div>@else<div class="overflow-x-auto"><table class="min-w-full text-left"><thead class="border-b border-gray-100 bg-gray-50 dark:border-gray-800 dark:bg-gray-900/40"><tr class="text-xs uppercase tracking-[0.16em] text-gray-500"><th class="px-6 py-4">Condomínio</th><th class="px-6 py-4">Unidade</th><th class="px-6 py-4">Proprietário</th><th class="px-6 py-4">Locatário</th><th class="px-6 py-4"></th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@foreach($items as $item)<tr><td class="px-6 py-4">{{ $item->condominium?->name }}</td><td class="px-6 py-4">{{ $item->unit_number }}</td><td class="px-6 py-4">{{ $item->owner?->display_name ?: '—' }}</td><td class="px-6 py-4">{{ $item->tenant?->display_name ?: '—' }}</td><td class="px-6 py-4 text-right"><a href="{{ route('clientes.unidades.edit', $item) }}" class="rounded-lg border border-gray-200 px-3 py-2 text-xs font-medium">Editar</a></td></tr>@endforeach</tbody></table></div><div class="border-t border-gray-100 px-6 py-4 dark:border-gray-800">{{ $items->links() }}</div>@endif</div>
@endsection
