<?php

namespace App\Support;

class AncoraRouteCatalog
{
    public static function groups(): array
    {
        return [
            'dashboard' => [
                'label' => 'Painel e busca',
                'routes' => [
                    'dashboard.index' => 'Acessar dashboard executivo',
                    'busca.index' => 'Acessar busca global',
                    'logs.index' => 'Acessar logs e auditoria',
                    'changelog.index' => 'Acessar versionamento e changelog',
                ],
            ],
            'config' => [
                'label' => 'Configuracoes',
                'routes' => [
                    'config.index' => 'Acessar configuracoes',
                    'config.automation.documentation' => 'Abrir documentacao da automacao WhatsApp',
                    'config.automation.save' => 'Salvar configuracao da automacao WhatsApp',
                    'config.branding.save' => 'Salvar branding',
                    'config.favicon.save' => 'Salvar favicon',
                    'config.modules.save' => 'Salvar modulos',
                    'config.system-alert.save' => 'Salvar alerta global interno',
                    'config.smtp.save' => 'Salvar SMTP do sistema',
                    'config.billing-smtp.save' => 'Salvar SMTP de cobranca',
                    'config.billing-imap.save' => 'Salvar IMAP de cobranca',
                    'config.access-profiles.save' => 'Salvar perfil de acesso',
                    'config.access-profiles.delete' => 'Excluir perfil de acesso',
                    'config.tjes-factors.store' => 'Salvar indice TJES',
                    'config.demand-tags.store' => 'Cadastrar tag de demanda',
                    'config.demand-tags.update' => 'Editar tag de demanda',
                    'config.demand-tags.delete' => 'Excluir tag de demanda',
                    'config.servicos.store' => 'Cadastrar servico',
                    'config.servicos.update' => 'Editar servico',
                    'config.servicos.delete' => 'Excluir servico',
                    'config.status.store' => 'Cadastrar status',
                    'config.status.update' => 'Editar status',
                    'config.status.delete' => 'Excluir status',
                    'config.formas.store' => 'Cadastrar forma de envio',
                    'config.formas.update' => 'Editar forma de envio',
                    'config.formas.delete' => 'Excluir forma de envio',
                    'config.process-options.store' => 'Cadastrar configuracao de processo',
                    'config.process-options.update' => 'Editar configuracao de processo',
                    'config.process-options.delete' => 'Excluir configuracao de processo',
                    'config.users.store' => 'Cadastrar usuario',
                    'config.users.update' => 'Editar usuario',
                    'config.users.delete' => 'Excluir usuario',
                ],
            ],
            'clientes' => [
                'label' => 'Clientes',
                'routes' => [
                    'clientes.index' => 'Acessar modulo clientes',
                    'clientes.export' => 'Exportar relatorios do modulo clientes',
                    'clientes.avulsos' => 'Listar avulsos',
                    'clientes.avulsos.create' => 'Novo avulso',
                    'clientes.avulsos.store' => 'Salvar avulso',
                    'clientes.avulsos.edit' => 'Editar avulso',
                    'clientes.avulsos.update' => 'Atualizar avulso',
                    'clientes.avulsos.delete' => 'Excluir avulso',
                    'clientes.contatos' => 'Listar contatos',
                    'clientes.contatos.create' => 'Novo contato',
                    'clientes.contatos.store' => 'Salvar contato',
                    'clientes.contatos.edit' => 'Editar contato',
                    'clientes.contatos.update' => 'Atualizar contato',
                    'clientes.contatos.delete' => 'Excluir contato',
                    'clientes.condominos' => 'Listar condominos',
                    'clientes.portal-users.index' => 'Listar usuarios do portal',
                    'clientes.portal-users.store' => 'Cadastrar usuario do portal',
                    'clientes.portal-users.update' => 'Atualizar usuario do portal',
                    'clientes.portal-users.delete' => 'Excluir usuario do portal',
                    'clientes.condominios' => 'Listar condominios',
                    'clientes.condominios.create' => 'Novo condominio',
                    'clientes.condominios.store' => 'Salvar condominio',
                    'clientes.condominios.edit' => 'Editar condominio',
                    'clientes.condominios.update' => 'Atualizar condominio',
                    'clientes.condominios.delete' => 'Excluir condominio',
                    'clientes.unidades' => 'Listar unidades',
                    'clientes.unidades.create' => 'Nova unidade',
                    'clientes.unidades.store' => 'Salvar unidade',
                    'clientes.unidades.edit' => 'Editar unidade',
                    'clientes.unidades.update' => 'Atualizar unidade',
                    'clientes.unidades.delete' => 'Excluir unidade',
                    'clientes.config' => 'Configurar tipos de clientes',
                    'clientes.config.types.store' => 'Cadastrar tipo',
                    'clientes.attachments.download' => 'Baixar anexo cliente',
                    'clientes.attachments.delete' => 'Excluir anexo cliente',
                ],
            ],
            'cobrancas' => [
                'label' => 'Cobranca',
                'routes' => [
                    'cobrancas.dashboard' => 'Acessar dashboard de cobranca',
                    'cobrancas.index' => 'Listar OS de cobranca',
                    'cobrancas.create' => 'Nova OS de cobranca',
                    'cobrancas.store' => 'Salvar OS de cobranca',
                    'cobrancas.import.index' => 'Acessar importacao de inadimplencia',
                    'cobrancas.import.preview' => 'Analisar planilha de inadimplencia',
                    'cobrancas.import.show' => 'Visualizar lote de importacao de inadimplencia',
                    'cobrancas.import.process' => 'Processar lote de inadimplencia',
                    'cobrancas.billing.report' => 'Acessar relatorio de faturamento de cobranca',
                    'cobrancas.billing.report.pdf' => 'Exportar PDF do relatorio de faturamento',
                    'cobrancas.agreement.edit' => 'Editar termo de acordo da OS',
                    'cobrancas.agreement.save' => 'Salvar customizacao do termo de acordo',
                    'cobrancas.agreement.pdf' => 'Gerar PDF do termo de acordo',
                    'cobrancas.monetary.preview' => 'Simular atualizacao monetaria TJES',
                    'cobrancas.monetary.store' => 'Salvar memoria de calculo TJES',
                    'cobrancas.monetary.apply' => 'Aplicar atualizacao monetaria na OS',
                    'cobrancas.monetary.pdf' => 'Gerar PDF da memoria de calculo TJES',
                    'cobrancas.show' => 'Visualizar OS de cobranca',
                    'cobrancas.edit' => 'Editar OS de cobranca',
                    'cobrancas.update' => 'Atualizar OS de cobranca',
                    'cobrancas.delete' => 'Excluir OS de cobranca',
                    'cobrancas.timeline.store' => 'Adicionar andamento na OS de cobranca',
                    'cobrancas.attachments.upload' => 'Enviar anexo no GED da cobranca',
                    'cobrancas.attachments.download' => 'Baixar anexo do GED da cobranca',
                    'cobrancas.attachments.delete' => 'Excluir anexo do GED da cobranca',
                    'cobrancas.boleto.request' => 'Solicitar boletos para a administradora',
                    'cobrancas.email-history.show' => 'Visualizar espelho de e-mail da OS',
                    'cobrancas.email-history.download' => 'Baixar anexo do e-mail da OS',
                ],
            ],
            'processos' => [
                'label' => 'Processos',
                'routes' => [
                    'processos.dashboard' => 'Acessar dashboard de processos',
                    'processos.index' => 'Listar processos',
                    'processos.create' => 'Novo processo',
                    'processos.store' => 'Salvar processo',
                    'processos.show' => 'Visualizar processo',
                    'processos.edit' => 'Editar processo',
                    'processos.update' => 'Atualizar processo',
                    'processos.delete' => 'Excluir processo',
                    'processos.phases.store' => 'Cadastrar fase do processo',
                    'processos.attachments.upload' => 'Enviar anexo do processo',
                    'processos.attachments.download' => 'Baixar anexo do processo',
                    'processos.attachments.delete' => 'Excluir anexo do processo',
                    'processos.datajud.sync' => 'Sincronizar processo com DataJud',
                ],
            ],
            'contratos' => [
                'label' => 'Contratos',
                'routes' => [
                    'contratos.dashboard' => 'Acessar dashboard de contratos',
                    'contratos.index' => 'Listar contratos',
                    'contratos.create' => 'Novo contrato',
                    'contratos.store' => 'Salvar contrato',
                    'contratos.show' => 'Visualizar contrato',
                    'contratos.edit' => 'Editar contrato',
                    'contratos.update' => 'Atualizar contrato',
                    'contratos.delete' => 'Excluir contrato',
                    'contratos.duplicate' => 'Duplicar contrato',
                    'contratos.archive' => 'Arquivar contrato',
                    'contratos.rescind' => 'Rescindir contrato',
                    'contratos.preview.resolve' => 'Carregar preview editavel do contrato',
                    'contratos.generate-pdf' => 'Gerar PDF do contrato',
                    'contratos.download-pdf' => 'Baixar PDF do contrato',
                    'contratos.versions.view' => 'Visualizar versao do contrato',
                    'contratos.versions.download' => 'Baixar PDF da versao do contrato',
                    'contratos.attachments.upload' => 'Enviar anexo de contrato',
                    'contratos.attachments.download' => 'Baixar anexo de contrato',
                    'contratos.attachments.delete' => 'Excluir anexo de contrato',
                    'contratos.templates.index' => 'Listar templates de contrato',
                    'contratos.templates.create' => 'Novo template de contrato',
                    'contratos.templates.store' => 'Salvar template de contrato',
                    'contratos.templates.edit' => 'Editar template de contrato',
                    'contratos.templates.update' => 'Atualizar template de contrato',
                    'contratos.templates.delete' => 'Excluir template de contrato',
                    'contratos.categories.index' => 'Listar categorias de contrato',
                    'contratos.categories.store' => 'Salvar categoria de contrato',
                    'contratos.categories.update' => 'Atualizar categoria de contrato',
                    'contratos.categories.delete' => 'Excluir categoria de contrato',
                    'contratos.variables.index' => 'Listar variaveis de contrato',
                    'contratos.variables.update' => 'Atualizar variavel de contrato',
                    'contratos.reports.index' => 'Acessar relatorios de contratos',
                    'contratos.reports.export.csv' => 'Exportar CSV de contratos',
                    'contratos.reports.export.pdf' => 'Exportar PDF de contratos',
                    'contratos.settings.index' => 'Acessar configuracoes de contratos',
                    'contratos.settings.save' => 'Salvar configuracoes de contratos',
                ],
            ],
            'financeiro' => [
                'label' => 'Financeiro 360',
                'routes' => [
                    'financeiro.dashboard' => 'Acessar dashboard financeiro',
                    'financeiro.cash-flow.index' => 'Acessar fluxo de caixa',
                    'financeiro.cash-flow.store' => 'Cadastrar movimentacao no fluxo de caixa',
                    'financeiro.receivables.index' => 'Listar contas a receber',
                    'financeiro.receivables.create' => 'Nova conta a receber',
                    'financeiro.receivables.store' => 'Salvar conta a receber',
                    'financeiro.receivables.show' => 'Visualizar conta a receber',
                    'financeiro.receivables.edit' => 'Editar conta a receber',
                    'financeiro.receivables.update' => 'Atualizar conta a receber',
                    'financeiro.receivables.delete' => 'Excluir conta a receber',
                    'financeiro.receivables.duplicate' => 'Duplicar conta a receber',
                    'financeiro.receivables.settle' => 'Dar baixa em conta a receber',
                    'financeiro.receivables.parcel' => 'Parcelar conta a receber',
                    'financeiro.receivables.renegotiate' => 'Renegociar conta a receber',
                    'financeiro.receivables.receipt' => 'Gerar recibo de conta a receber',
                    'financeiro.receivables.pdf' => 'Gerar PDF de conta a receber',
                    'financeiro.receivables.attachments.upload' => 'Enviar anexo de conta a receber',
                    'financeiro.receivables.attachments.download' => 'Baixar anexo de conta a receber',
                    'financeiro.receivables.attachments.delete' => 'Excluir anexo de conta a receber',
                    'financeiro.payables.index' => 'Listar contas a pagar',
                    'financeiro.payables.create' => 'Nova conta a pagar',
                    'financeiro.payables.store' => 'Salvar conta a pagar',
                    'financeiro.payables.show' => 'Visualizar conta a pagar',
                    'financeiro.payables.edit' => 'Editar conta a pagar',
                    'financeiro.payables.update' => 'Atualizar conta a pagar',
                    'financeiro.payables.delete' => 'Excluir conta a pagar',
                    'financeiro.payables.duplicate' => 'Duplicar conta a pagar',
                    'financeiro.payables.settle' => 'Dar baixa em conta a pagar',
                    'financeiro.payables.attachments.upload' => 'Enviar anexo de conta a pagar',
                    'financeiro.payables.attachments.download' => 'Baixar anexo de conta a pagar',
                    'financeiro.payables.attachments.delete' => 'Excluir anexo de conta a pagar',
                    'financeiro.billing.index' => 'Acessar faturamento',
                    'financeiro.billing.generate-contract' => 'Gerar cobrancas a partir de contrato',
                    'financeiro.accounts.index' => 'Listar bancos e contas',
                    'financeiro.accounts.store' => 'Salvar conta financeira',
                    'financeiro.accounts.update' => 'Atualizar conta financeira',
                    'financeiro.accounts.delete' => 'Excluir conta financeira',
                    'financeiro.reconciliation.index' => 'Acessar conciliacao bancaria',
                    'financeiro.reconciliation.upload' => 'Importar extrato bancario',
                    'financeiro.reconciliation.conciliate' => 'Conciliar lancamento bancario',
                    'financeiro.collection.index' => 'Acessar cobrancas financeiras',
                    'financeiro.delinquency.index' => 'Acessar inadimplencia',
                    'financeiro.cost-centers.index' => 'Listar centros de custo',
                    'financeiro.cost-centers.store' => 'Salvar centro de custo',
                    'financeiro.cost-centers.update' => 'Atualizar centro de custo',
                    'financeiro.cost-centers.delete' => 'Excluir centro de custo',
                    'financeiro.categories.index' => 'Listar categorias financeiras',
                    'financeiro.categories.store' => 'Salvar categoria financeira',
                    'financeiro.categories.update' => 'Atualizar categoria financeira',
                    'financeiro.categories.delete' => 'Excluir categoria financeira',
                    'financeiro.installments.index' => 'Listar parcelamentos',
                    'financeiro.installments.show' => 'Visualizar parcelamento',
                    'financeiro.installments.store' => 'Salvar parcelamento',
                    'financeiro.installments.delete' => 'Excluir parcelamento',
                    'financeiro.reimbursements.index' => 'Listar reembolsos',
                    'financeiro.reimbursements.create' => 'Novo reembolso',
                    'financeiro.reimbursements.store' => 'Salvar reembolso',
                    'financeiro.reimbursements.edit' => 'Editar reembolso',
                    'financeiro.reimbursements.update' => 'Atualizar reembolso',
                    'financeiro.reimbursements.delete' => 'Excluir reembolso',
                    'financeiro.process-costs.index' => 'Listar custas processuais',
                    'financeiro.process-costs.create' => 'Nova custa processual',
                    'financeiro.process-costs.store' => 'Salvar custa processual',
                    'financeiro.process-costs.edit' => 'Editar custa processual',
                    'financeiro.process-costs.update' => 'Atualizar custa processual',
                    'financeiro.process-costs.delete' => 'Excluir custa processual',
                    'financeiro.accountability.index' => 'Acessar prestacao de contas',
                    'financeiro.accountability.pdf' => 'Gerar PDF de prestacao de contas',
                    'financeiro.dre.index' => 'Acessar DRE',
                    'financeiro.dre.pdf' => 'Gerar PDF da DRE',
                    'financeiro.reports.index' => 'Acessar relatorios financeiros',
                    'financeiro.export' => 'Exportar relatorios financeiros',
                    'financeiro.import.template' => 'Baixar modelo de importacao financeira',
                    'financeiro.import.preview' => 'Analisar importacao financeira',
                    'financeiro.import.show' => 'Visualizar lote de importacao financeira',
                    'financeiro.import.process' => 'Processar lote de importacao financeira',
                    'financeiro.settings.index' => 'Acessar configuracoes financeiras',
                    'financeiro.settings.save' => 'Salvar configuracoes financeiras',
                ],
            ],
            'demandas' => [
                'label' => 'Demandas',
                'routes' => [
                    'demandas.dashboard' => 'Acessar dashboard de demandas',
                    'demandas.kanban' => 'Acessar kanban de demandas',
                    'demandas.index' => 'Listar demandas',
                    'demandas.create' => 'Nova demanda',
                    'demandas.store' => 'Salvar demanda',
                    'demandas.show' => 'Visualizar demanda',
                    'demandas.update' => 'Atualizar demanda',
                    'demandas.tag.update' => 'Mover demanda no kanban',
                    'demandas.reply' => 'Responder demanda',
                    'demandas.attachments.download' => 'Baixar anexo de demanda',
                ],
            ],
            'propostas' => [
                'label' => 'Propostas',
                'routes' => [
                    'propostas.dashboard' => 'Acessar dashboard de propostas',
                    'propostas.index' => 'Listar propostas',
                    'propostas.export.csv' => 'Exportar CSV',
                    'propostas.create' => 'Nova proposta',
                    'propostas.store' => 'Salvar proposta',
                    'propostas.show' => 'Visualizar proposta',
                    'propostas.print' => 'Imprimir proposta',
                    'propostas.edit' => 'Editar proposta',
                    'propostas.update' => 'Atualizar proposta',
                    'propostas.delete' => 'Excluir proposta',
                    'propostas.attachments.upload' => 'Enviar anexo de proposta',
                    'propostas.attachments.download' => 'Baixar anexo de proposta',
                    'propostas.attachments.delete' => 'Excluir anexo de proposta',
                    'propostas.document.edit' => 'Editar documento premium',
                    'propostas.document.save' => 'Salvar documento premium',
                    'propostas.document.preview' => 'Visualizar documento premium',
                    'propostas.document.pdf' => 'PDF/print documento premium',
                ],
            ],
        ];
    }

    public static function flat(): array
    {
        $flat = [];
        foreach (self::groups() as $group) {
            foreach ($group['routes'] as $routeName => $label) {
                $flat[$routeName] = $label;
            }
        }

        return $flat;
    }
}
